GET http://localhost:6900/users

###

POST http://localhost:6900/register
Content-Type: application/json

{
    "username": "hoangminh0824",
    "password": "password123"
}

###

POST http://localhost:6900/users/login
Content-Type: application/json

{
    "username": "hoangminh0824",
    "password": "password123"
}